### ISSUE TITLE
[Bug]: 3D Models not being shown

### ISSUE THREAD

**Issue by DuneSciFye** [Kas-tle/java2bedrock.sh#10457]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/10454

### Expected Output

3D Models to be shown

### Actual Output

3D models are not shown

### Additional Context

Only happens when you select Rename Model Files to true.
![image](https://github.com/Kas-tle/java2bedrock.sh/assets/65089425/f00eb982-6170-4443-8581-c828c577c98a)

**Comment by Horus891** [comment]
Can you please send the java file? I'm not a helper, I just want to check if the files are compiled correctly

**Comment by DuneSciFye** [comment]
[generated.zip](https://github.com/Kas-tle/java2bedrock.sh/files/12296275/generated.zip)
