### ISSUE TITLE
3D Models Not Showing[Bug]: 

### ISSUE THREAD

**Issue by RittroOfficial** [Kas-tle/java2bedrock.sh#10604]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/5786868122/workflow

### Expected Output

I converted my java pack to bedrock pack and I'm expecting to convert the blocks textures also. But still it is the same like before for bedrock users. Other custom items texture is not also showing. Other items just show as paper icon.

Here's the link for the screenshot of bedrock client
https://drive.google.com/file/d/1kMvylY4jezgV5oNCi_0_S-yync2UaUvT/view?usp=sharing

Also. I'm receiving warnings in my console that the file exceeds 80 characters in the converted resource pack

### Actual Output

07.08 15:24:01 [Server] WARN [Geyser-Spigot] The resource pack geyser_resources.mcpack has a file in it that meets or exceeds 80 characters in its path (attachables/iaspecial_swords/ia_auto_gen/elucidator_sword.gmdl_58b680b.attachable.json, 86 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.
07.08 15:24:01 [Server] WARN [Geyser-Spigot] The resource pack geyser_resources.mcpack has a file in it that meets or exceeds 80 characters in its path (attachables/iaspecial_swords/item/closed_lightsaber.gmdl_030ca24.attachable.json, 80 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.
07.08 15:24:01 [Server] WARN [Geyser-Spigot] The resource pack geyser_resources.mcpack has a file in it that meets or exceeds 80 characters in its path (attachables/_iainternal/ia_auto_gen/icon_arrow_chest.gmdl_42b5919.attachable.json, 81 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.
07.08 15:24:01 [Server] WARN [Geyser-Spigot] The resource pack geyser_resources.mcpack has a file in it that meets or exceeds 80 characters in its path (attachables/_iainternal/ia_auto_gen/icon_back_orange.gmdl_5d9b87a.attachable.json, 81 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.

**Comment by Kas-tle** [comment]
1. It doesn't convert blocks
2. To resolve the path issue, use shorter paths
