### ISSUE TITLE
[Bug]: 3D model and 2D icon not be shown

### ISSUE THREAD

**Issue by luongcongtandpt** [Kas-tle/java2bedrock.sh#10889]
### Conversion Issue Link

https://github.com/Hahaa13/java2bedrock.sh/actions/runs/5840565585

### Expected Output

3D model not showing

### Actual Output

after convert , 3D model is not show in bedrock platform , did i do sthing wrong , help me pls

### Additional Context

Did i do sthing wrong bruhhh , pls help me as fast as possible

**Comment by Kas-tle** [comment]
This is a different repo. Forks are not supported.
