### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by ijgeoffrey** [Kas-tle/java2bedrock.sh#1189]
### Java Pack Direct Download URL

https://download.mc-packs.net/pack/8ee69126e31c541760c2cab750ce4e03ee21d35f.zip

### Default Assets Version

1.19.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Hahaa13** [comment]
nice pack
