### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DevChoriflan** [Kas-tle/java2bedrock.sh#12667]
### Conversion Issue Link

https://drive.google.com/uc?export=download&id=19Fddm0Mk8WtnoBTwRX8tYPdn8q-p_WCt

### Expected Output

Necesitaba un pack de texturas para items y armaduras personalizadas para bedrock en GeyserMC

### Actual Output

Me sale un error a la hora de convertir el pack de texturas

**Comment by Klisee** [comment]
Si estas usando algo para convertir debes sacar el Output y copiar el enlace directamente

**Comment by Kas-tle** [comment]
No error was provided so closing.
