### ISSUE TITLE
[Bug]: pack does not convert

### ISSUE THREAD

**Issue by Erwandawa123** [Kas-tle/java2bedrock.sh#14432]
### Conversion Issue Link

https://www.mediafire.com/file/d7ef3c19c4tdoed/Survival_Expansion_Textures.zip/file?dkey=o7219wcfs3z&r=813

### Expected Output

It should have had a succesfull conversion

### Actual Output

The converter said that the pack.mcmeta was missing and it finshed with exit code 1, but when I look into the zip I see the pack.mcmeta

**Comment by Kas-tle** [comment]
A mediafire link is not a direct download link.
