### ISSUE TITLE
[Bug]: Not converting properly.

### ISSUE THREAD

**Issue by SamGamerYT** [Kas-tle/java2bedrock.sh#1697]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/1696

### Expected Output

It should be somewhat similar.

### Actual Output

[https://cdn.discordapp.com/attachments/396157591614521356/1043937795267383406/Weird.png](url)
It's looking weird, Previously when converted on this Conversion 

https://github.com/Kas-tle/java2bedrock.sh/issues/1473
Everything looked great but I can't use that as it's old for modelengine, Did something change?

**Comment by Kas-tle** [comment]
You're missing GeyserOptionalPack. This is not a bug with the converter. Please use discussions for help with conversion.

**Comment by SamGamerYT** [comment]
holy shit you are right
