### ISSUE TITLE
Cool dynamic surrounding

### ISSUE THREAD

**Issue by Carftserver** [Kas-tle/java2bedrock.sh#170]
### Java Pack Direct Download URL

https://www.mediafire.com/file/963d3vt04qiu91d/DynamicSurroundings_%255BPack_1.17-1.18%255D.zip/file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kas-tle** [comment]
@Carftserver that is not a direct link
