### ISSUE TITLE
[Bug]: [ERROR] Dependency spritesheet-js must be installed to proceed

### ISSUE THREAD

**Issue by uploadx10** [Kas-tle/java2bedrock.sh#18]
### Conversion Issue Link

-

### Expected Output

./converter.sh rp.zip

### Actual Output

I have installed spritesheet-js, the system can't find it.

### Additional Context

use

echo "export PATH=$PATH:$(npm config --global get prefix)/bin" >> ~/.bashrc && source ~/.bashrc

not working

**Comment by uploadx10** [comment]
https://i.imgur.com/kRvAOly.png

**Comment by Kas-tle** [comment]
Hi, as is stated on the submission page for bugs, you must link to a conversion run for the bug to be considered. You have not done this. I noticed that you did also submit a conversion run, for which you did not submit a direct link for your pack. The link you submitted is: https://drive.google.com/uc?export=download&id=1nxaVTxLc3R2bT3Wkx3prYvGr3U9gkJ4-

Upon downloading, notice that the directory structure contains an enclosing folder for the assets folder and pack.mcmeta file. This is not a valid resource pack.
![image](https://user-images.githubusercontent.com/26531652/170832941-950a67dd-b3d1-4f33-9754-2c20d9eac124.png)

You must instead zip up the assets folder and pack.mcmeta file, not the enclosing folder. The structure of such a zip file should look like this:
![image](https://user-images.githubusercontent.com/26531652/170833037-4686d748-de8d-4226-906b-35d876bc5de0.png)

As for your other issue, as stated on this bug submission page:

> If you simply need help with running the converter locally, please use the [Converter Help](https://github.com/Kas-tle/java2bedrock.sh/discussions/categories/converter-help) category on the discussions page.

Given this, please use the converter help category on the discussions page for troubleshooting your personal setup.
