### ISSUE TITLE
Pack [Pack]: 

### ISSUE THREAD

**Issue by aamoon05** [Kas-tle/java2bedrock.sh#18748]
### Java Pack Direct Download URL

https://drive.google.com/uc?export=download&id=1Si-DBuXXTywkQAklj9QwspkzHesbc5xG

### Default Assets Version

1.20.1

### Block Material

alpha_test

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by IkyMax** [comment]
hey dude! you should upload your pack to mc-packs.net for this tool!
