### ISSUE TITLE
Converter seems to be broken and saying node 20 is required.

### ISSUE THREAD

**Issue by DontMessWithDis** [Kas-tle/java2bedrock.sh#19303]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/7671407829

### Expected Output

Expected a texture pack conversion

### Actual Output

Recieved an incomplete texture pack.
[Pack Files (7).zip](https://github.com/Kas-tle/java2bedrock.sh/files/14067778/Pack.Files.7.zip)

**Comment by Kas-tle** [comment]
It's saying node16 actions are deprecated. The converter is still running.
