### ISSUE TITLE
upgrade converter 1.20.4

### ISSUE THREAD

**Issue by Twit222** [Kas-tle/java2bedrock.sh#19772]
### Conversion Issue Link

Update the converter to 1.20.4

### Expected Output

Update the converter to 1.20.4

### Actual Output

Update the converter to 1.20.4

### Additional Context

Update the converter to 1.20.4

**Comment by unknowghost0** [comment]
how is this a bug

**Comment by Kas-tle** [comment]
It is already 1.20.4
