### ISSUE TITLE
[Bug]: The texture is the  same in the hotbar

### ISSUE THREAD

**Issue by JohnnyX071** [Kas-tle/java2bedrock.sh#230]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/229

### Expected Output

The item does indeed change when you are holding it in your hand, but on the hotbar its the  same

### Actual Output

The texture should change on the hotbar too. I am not if I did something wrong but on java, it works fine

### Additional Context

![image](https://user-images.githubusercontent.com/63922728/183501120-87f644bf-3e21-40bf-bbd2-a77c513b4203.png)

**Comment by Kas-tle** [comment]
The converter does not generate sprites of the item. That is on you to do if you wish.

**Comment by JohnnyX071** [comment]
Is it going to be added? Also how to do that?

**Comment by Kas-tle** [comment]
No it will not as there's not really a good way to do it. It would be best to do by hand as simply downscaling a render of the model would produce a bad output. Refer to the guide I linked in Geyser Discord for how to set icons.

**Comment by JohnnyX071** [comment]
So this is just for the icons? https://github.com/GeyserCustomModelData/HowTo Kinda confused

**Comment by Kas-tle** [comment]
It explains how you would setup icons. I think you need to familiarize yourself with the way Bedrock resource packs are setup. https://wiki.bedrock.dev/ is a good resource, as well as the Bedrock Addons Discord, which you can find linked on there.

**Comment by JohnnyX071** [comment]
Ok, maybe its the most stupid thing you have ever heard but do I just replace the icon with the texture name of the item I want it to be?
![image](https://user-images.githubusercontent.com/63922728/183506389-30091135-20ba-4e6d-8667-47b0fe6fa211.png)

**Comment by Kas-tle** [comment]
The short name can go there, but then you must define a texture path for the short name in item_textures.json

**Comment by JohnnyX071** [comment]
It is already like that though.
![image](https://user-images.githubusercontent.com/63922728/183583292-f4676b01-ccf0-4082-b051-89f413aa6d33.png)

**Comment by JohnnyX071** [comment]
> The short name can go there, but then you must define a texture path for the short name in item_textures.json

So what do I do?
