### ISSUE TITLE
[Bug]: Update to node 20

### ISSUE THREAD

**Issue by CasperTimmy** [Kas-tle/java2bedrock.sh#23639]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/23623

### Expected Output

A converted texture pack

### Actual Output

get-pack-info
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: zentered/issue-forms-body-parser@v1.5.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

convert-pack
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/setup-node@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

post-result
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peter-evans/create-or-update-comment@v2, peter-evans/close-issue@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Kas-tle** [comment]
The deprecation warning is a warning. That does not mean the converter isn't working.
