### ISSUE TITLE
[Bug]: pack.mcmeta is missing but it's not?

### ISSUE THREAD

**Issue by Javimoa95** [Kas-tle/java2bedrock.sh#26655]
### Conversion Issue Link

https://www.dropbox.com/scl/fi/0gh5bjhfpl7ez2yh3f6ly/generated-5.zip?rlkey=xl6krvx43ammvt3gjc7pdky4g&st=8dyhtxi4&dl=1

### Expected Output

I expected a successful conversion

### Actual Output

Issue saying this
![image](https://github.com/Kas-tle/java2bedrock.sh/assets/72030264/26503ab5-a4cc-4e6a-8e95-5cb82d20e79b)

### Additional Context

I dissabled both protections so it zips with the pack.mcmeta and all the necessary files and it sitll doesn't work

**Comment by Kas-tle** [comment]
Please try a different file host and ensure the file can be unzipped properly.

**Comment by Javimoa95** [comment]
Wdym a "different file host"? It's a regular texturepack. I tried different stuff also since this:
- unZipping the file and zipping again
- Using ItemsAdder's output for it
- Using WinRar to check for issues/viruses and see if that's the issue
