### ISSUE TITLE
[Bug]: 1.19.3 Converter results in 29.6kb Empty Pack

### ISSUE THREAD

**Issue by TheCashFire** [Kas-tle/java2bedrock.sh#2740]
### Conversion Issue Link

https://download.mc-packs.net/pack/e72b865e820948b5e70bb4b8058ceb2d433f723f.zip

### Expected Output

A pack?

### Actual Output

A folder with the expected files, which are all empty. 0kb, nothing inside.

### Additional Context

Not sure what the issue is, this was working on the 1.19.2 converter last month, can't figure out the issue now.

**Comment by Kas-tle** [comment]
https://github.com/Kas-tle/java2bedrock.sh/actions/runs/3820572226/jobs/6498965055#step:6:229
```
jq: error (at ./assets/minecraft/models/item/interface/green/arrow_left2.json:1): Invalid numeric literal at line 13890, column 0
```
![image](https://user-images.githubusercontent.com/26531652/210210142-10bd03ec-8dca-4c0f-beb0-ca200373bca5.png)
