### ISSUE TITLE
[Pack]: LoungeWorld Server Pack

### ISSUE THREAD

**Issue by YstalX** [Kas-tle/java2bedrock.sh#27672]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/zoe77u609jo6w03sfk214/generated.zip?rlkey=bz2n0lq0od3pireppo55mmpkd&st=biu3kmu4&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by knokko** [comment]
It looks like the file at https://www.dropbox.com/scl/fi/zoe77u609jo6w03sfk214/generated.zip?rlkey=bz2n0lq0od3pireppo55mmpkd&st=biu3kmu4&dl=0 is already deleted. I recommend trying again, but replacing the dl=0 at the end of the url with dl=1, like this: https://www.dropbox.com/scl/fi/zoe77u609jo6w03sfk214/generated.zip?rlkey=bz2n0lq0od3pireppo55mmpkd&st=biu3kmu4&dl=1
