### ISSUE TITLE
[Pack]: pppp

### ISSUE THREAD

**Issue by Lilnusnus666** [Kas-tle/java2bedrock.sh#27689]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/xfoq6kypqfn2hlpzvt2h9/merged-10.zip?rlkey=8o87lugt9v01wbc39iauuijuj&st=md7yztb9&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
