### ISSUE TITLE
[Bug]: only white texture 3d item

### ISSUE THREAD

**Issue by qwertyuiop1923** [Kas-tle/java2bedrock.sh#27726]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/27698

### Expected Output

Only White Paper

### Actual Output

Subnautica's textures and 3D items should have come out. But no matter how much I try to convert it to play with my friend, it comes out like a square of white paper. Someone told me to open it in the blockbench, and when I opened it, I couldn't see the texture

**Comment by Kas-tle** [comment]
This occurs when you have a missing texture.
