### ISSUE TITLE
Says missing pack.mcmeta when is not missing and is in the root of the zip file.

### ISSUE THREAD

**Issue by JoelTapiaSalvador** [Kas-tle/java2bedrock.sh#27934]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/27932

### Expected Output

Expected conversion succeful since the ressource pack works perfectly in java.

### Actual Output

Have tried multiple times with different download links directly to the zip pile with pack.mcmeta in the root, tested it personally. Every times says:
> [input_pack.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of input_pack.zip or
        input_pack.zip.zip, and cannot find input_pack.zip.ZIP, period.
       
And then throws the error:
>[ERROR] Invalid resource pack! The pack.mcmeta file does not exist. Is the resource pack improperly compressed in an enclosing folder?
Error: Process completed with exit code 1.

Screenshot of the Output:
![Screenshot 2024-06-11 142924](https://github.com/Kas-tle/java2bedrock.sh/assets/101792242/41dbcfda-01d8-471c-ab53-db1f9a1fc90d)

### Additional Context

Have used different ways of providing the pack, all, when me using it, diretly downloads the .zip file with the pack.mcmeta as root as specified it should do in the action. Links that I have used:
- https://onedrive.live.com/download?resid=B8A985E28A426045%21161068&authkey=!AMh3ck9jphi8jaU
- https://drive.google.com/uc?export=download&id=1l37CuMqsSxEu5dDikmoO4XTlAjyeHMpj

**Comment by knokko** [comment]
Your second link failed because it requires a log-in to Google Drive, which the converter bot can't. I have no clue why the first link failed, but I uploaded your pack to another site, and that seemed to work: https://github.com/Kas-tle/java2bedrock.sh/issues/29153
