### ISSUE TITLE
[Bug]: 无法转换

### ISSUE THREAD

**Issue by New66666666666** [Kas-tle/java2bedrock.sh#27949]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/9470156898

### Expected Output

无法转换，文件是可以被mc客户端识别不知道为什么一直不能转换

### Actual Output

一直转换失败

### Additional Context

mc客户端是可以识别到这个材质包的

**Comment by knokko** [comment]
Your Java pack **direct download link** is https://www.alipan.com/t/CIfJMq1gGNwVZy651t01, which is **not** a direct download link, but looks like some kind of preview webpage. When you visit a **direct** download link in your web browser, it should **instantly download** the file. For instance, http://knokko.github.io/resourcedumps/HoneySword.zip is a direct download link.

**Comment by New66666666666** [comment]
My link is to a netbook. Can't this work too?
&nbsp;


。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月29日(星期六) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kas-tle/java2bedrock.sh] [Bug]: 无法转换 (Issue #27949)














 
Your Java pack direct download link is https://www.alipan.com/t/CIfJMq1gGNwVZy651t01, which is not a direct download link, but looks like some kind of preview webpage. When you visit a direct download link in your web browser, it should instantly download the file. For instance, http://knokko.github.io/resourcedumps/HoneySword.zip is a direct download link.

**Comment by knokko** [comment]
I don't have a netbook myself, so I don't know if it can work,, but I do know that your current link is not good enough. I would recommend something like https://mc-packs.net (this website is actually made for hosting server resourcepacks, but it provides a direct download link, which you need)
