### ISSUE TITLE
[Bug]: My all resource pack is say " pack-meta? " error  

### ISSUE THREAD

**Issue by mocxlbor** [Kas-tle/java2bedrock.sh#2827]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/3838068734

### Expected Output

pls help

### Actual Output

[ERROR] Invalid resource pack! The pack.mcmeta file does not exist. Is the resource pack improperly compressed in an enclosing folder?

**Comment by Kas-tle** [comment]
Not a valid issue. The error you provide here is not the error in the action you reference.

Per the error `[ERROR] Invalid resource pack! No item or block folders exist. No predicate definitions be found.`: 

![image](https://user-images.githubusercontent.com/26531652/210576268-81c615e2-997b-48d3-a52e-7fc50dfcac4a.png)

This converter only converts models defined by custom model data or damage predicates. The pack you provided does not have any, so there is nothing for the converter to do.
