### ISSUE TITLE
[Bug]: Bot says pack.mcmeta file doesn't exist but it does

### ISSUE THREAD

**Issue by MeowkaTheCat** [Kas-tle/java2bedrock.sh#28988]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/28962

### Expected Output

It works fine on java so i thought it would convert without any problems

### Actual Output

![IMG_20240627_174819](https://github.com/Kas-tle/java2bedrock.sh/assets/148512520/19c77442-86ba-4691-9d95-4a8d4b70ddf8)

### Additional Context

I tried converting the same resource pack 4 times, but the output is the same

**Comment by knokko** [comment]
The Java pack direct download URL is https://github.com/MeowkaTheCat/Model-engine-resource-pack-minecraft, which yields a 404 (Page not found) when I try to visit the page. Did you already remove the resourcepack from your Github? Or is it a private repository maybe?

**Comment by MeowkaTheCat** [comment]
Its a private repository

**Comment by MeowkaTheCat** [comment]
Ok, i made it public

**Comment by MeowkaTheCat** [comment]
Thank you very much, ill say if it works

**Comment by MeowkaTheCat** [comment]
Thank you! It really worked
