### ISSUE TITLE
[Bug]: No Sounds Converted

### ISSUE THREAD

**Issue by SilentHyuu** [Kas-tle/java2bedrock.sh#29499]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/29497

### Expected Output

Im need sound of the texture pack

### Actual Output

The sounds is missing

### Additional Context

Aahhh i feel good but its a bug please fix it

**Comment by AriqMicin** [comment]
You should convert it manually
there is no way to make it auto

**Comment by Kas-tle** [comment]
Sounds are not supported.
