### ISSUE TITLE
[Bug]: Issue with geyser_mappings.json

### ISSUE THREAD

**Issue by Caveel20** [Kas-tle/java2bedrock.sh#30893]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/10028676202

### Expected Output

I Just Want to Know How to Overcome geyser_mappings.json that Does Not Have Text 

### Actual Output

geyser_mappings.json that has no text cannot be uploaded to the geyser folder 

### Additional Context

Please help me overcome it

**Comment by Kas-tle** [comment]
No entries means you don't have any predicate based models to convert.
