### ISSUE TITLE
[Bug]: pack.mcmeta error?

### ISSUE THREAD

**Issue by woodypegasus382** [Kas-tle/java2bedrock.sh#31077]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/10063682672/job/27818955646

### Expected Output

done

### Actual Output

![image](https://github.com/user-attachments/assets/a1c06d30-7fb2-43b3-91a9-e363a20fcb12)

### Additional Context

I use
https://willis.lnstw.xyz/pack/%E9%81%BA%E6%B5%B7%E9%AF%A8%E8%90%BD%E4%BC%BA%E6%9C%8D%E5%99%A8-%E5%B0%88%E7%94%A8%E6%9D%90%E8%B3%AA%E5%8C%85.zip
and
https://willis.lnstw.xyz/pack/be%E9%81%BA%E6%B5%B7%E9%AF%A8%E8%90%BD%E4%BC%BA%E6%9C%8D%E5%99%A8-%E5%B0%88%E7%94%A8%E6%9D%90%E8%B3%AA%E5%8C%85.zip
but still wrong

**Comment by Kas-tle** [comment]
Please try a different file host.
