### ISSUE TITLE
[Bug]: 2D image not show?

### ISSUE THREAD

**Issue by maximumero** [Kas-tle/java2bedrock.sh#31123]
### Conversion Issue Link

https://i.imgur.com/SG7cECh.png

### Expected Output

image show as 2d 

### Actual Output

image not show and crash

### Additional Context

https://lobfile.com/file/fxdxDVH8.zip
this is my work and i dont know where i'm wrong

**Comment by Kas-tle** [comment]
For icons for models, follow the instructions in the README.
