### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by goldenarrow153** [Kas-tle/java2bedrock.sh#31488]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/31473

### Expected Output

Menu ModelMenu Models, Rank Models, Bossbar Model Missing And the console also gives an error

### Actual Output

[log.txt](https://github.com/user-attachments/files/16428526/log.txt)

**Comment by goldenarrow153** [comment]
buda java pack 
[java itemsadder pack.zip](https://github.com/user-attachments/files/16428563/java.itemsadder.pack.zip)

**Comment by Kas-tle** [comment]
GUIs are not supported.
