### ISSUE TITLE
Javaa [Pack]: 

### ISSUE THREAD

**Issue by Azelonyth** [Kas-tle/java2bedrock.sh#35032]
### Java Pack Direct Download URL

https://drive.google.com/file/d/1TElgCF8yK0ifQdDpEHPlwkXLSpqNnEAO/view?usp=drivesdk

### Default Assets Version

1.20.1

### Block Material

alpha_test

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

true

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by moda-haijiao** [comment]
Your download link isn't a direct link.
