### ISSUE TITLE
[Pack]: AZURA BUNDLE 

### ISSUE THREAD

**Issue by Sanydavalaper** [Kas-tle/java2bedrock.sh#37194]
### Java Pack Direct Download URL

http://atlas.oraxen.com:8080/pack.zip?id=feb24cbad258e5193d8f2b97b3afc5c8d93deccc

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by KICHIROSHIN** [comment]
./converter.sh MyResourcePack.zip -w "false" -m "MyBedrock.mcpack" -a "entity_alphatest_one_sided" -b "alpha_test" -f "null" -v "1.18.2"
