### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MohammadAlawieh** [Kas-tle/java2bedrock.sh#3945]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/4095205194

### Expected Output

i am expecting some files and textures in the pack

### Actual Output

the pack is coming out to be empty, no textures, no mapping, nothing in the files

### Additional Context

this problem is only happening to 1 pack, I've tried the converter on another pack and it worked

Note: the pack is working for java and have 0 issues

**Comment by Kas-tle** [comment]
Per the log you have malformed JSON in your pack. Please always read the log before opening an issue. https://github.com/Kas-tle/java2bedrock.sh/actions/runs/4095205194/jobs/7061949606#step:6:232
