### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MG141** [Kas-tle/java2bedrock.sh#4553]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh

### Expected Output

[+] Dependency jq-1.6 satisfied
[+] Dependency sponge satisfied
[+] Dependency imagemagick satisfied
[+] Dependency spritesheet-js satisfied

### Actual Output

[+] Dependency jq-1.6 satisfied
[+] Dependency sponge satisfied
[+] Dependency imagemagick satisfied
[ERROR] Dependency spritesheet-js must be installed to proceed
See https://www.npmjs.com/package/spritesheet-js
Exiting script...

### Additional Context

Even after running instakll script for spritesheet manually, in the same folder as script and adding a global path to it, the convertion script still cannot start.

**Comment by Kas-tle** [comment]
Thank you for completely failing to read the notice provided when opening an issue.

> In order to file a bug report, you must first attempt to convert your pack via the [pack conversion action](https://github.com/Kas-tle/java2bedrock.sh/issues/new?assignees=&labels=conversion&template=pack-conversion.yml&title=%5BPack%5D%3A+) and include a link to the resulting issue. Any issues without such a link will be automatically rejected.
If you simply need help with running the converter locally, please use the [Converter Help](https://github.com/Kas-tle/java2bedrock.sh/discussions/categories/converter-help) category on the discussions page.
