### ISSUE TITLE
[Pack]: normak

### ISSUE THREAD

**Issue by Carftserver** [Kas-tle/java2bedrock.sh#4787]
### Java Pack Direct Download URL

https\://www.dropbox.com/s/jhtne1ltnd9fklm/resourcepack%20%283%29.zip?dl\=1

### Default Assets Version

None

### Block Material

blend

### Attachable Material

entity

### Archive Scratch Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Hahaa13** [comment]
a normal pack
