### ISSUE TITLE
[Bug]: Customs GUIS | emojis | fonts?

### ISSUE THREAD

**Issue by dipolo12q** [Kas-tle/java2bedrock.sh#5143]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/5111

### Expected Output

Emojis, guis, icons are displayed correctly in the java version.

### Actual Output

Is there a way to fix some GUIS that Bedrock players see as invisible or non-textured? besides that some 2d icons are not showing. I also got the "duplicate name" problem. I have emojis in the resourcepack and they come out as unknown characters (squares with question marks) I would like to know if there is any way to fix that. I understand that emojis and GUIS are related because if I'm not mistaken both are fonts.

**Comment by Hahaa13** [comment]
No support converter font and gui
How to make gui and font ?
GUI: use json-ui
FONT: ... all in the https://wiki.bedrock.dev

**Comment by Kas-tle** [comment]
The converter only supports custom model data and damage based predicates that reference 2D and 3D models.
