### ISSUE TITLE
[Bug]: Duplicate Custommodeldata value

### ISSUE THREAD

**Issue by DJelly4K** [Kas-tle/java2bedrock.sh#60]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/59

### Expected Output

Because the custommodeldata value of different items may be the same, and they are named according to the converted item id, it is easy to cause the item to be named the same. It is recommended to add the original item name to the converted item id
for example:
gmdl_114514 (original) => gmdl_iron_sword_114514 (workaround)

### Actual Output

/

### Additional Context

i use machine translate

**Comment by Kas-tle** [comment]
Hello, the number after the item has nothing to do with the actual custom model data value. All items are simply numbered which all instances of predicate overrides are found. Furthermore, in the conversion run you link has not even finished, so I am not sure why you already expect there to be duplicate names.

**Comment by DJelly4K** [comment]
> 

I tested it in local before, but some icons in this pack will be ignored

**Comment by DJelly4K** [comment]
> Hello, the number after the item has nothing to do with the actual custom model data value. All items are simply numbered which all instances of predicate overrides are found. Furthermore, in the conversion run you link has not even finished, so I am not sure why you already expect there to be duplicate names.

![image](https://user-images.githubusercontent.com/68630033/175819974-42961b7a-5a38-473f-83b5-16fba0c3bf2b.png)
like this

**Comment by DJelly4K** [comment]
> Hello, the number after the item has nothing to do with the actual custom model data value. All items are simply numbered which all instances of predicate overrides are found. Furthermore, in the conversion run you link has not even finished, so I am not sure why you already expect there to be duplicate names.

![image](https://user-images.githubusercontent.com/68630033/175820006-61b4dace-94c0-4f32-8552-225c0891106f.png)

**Comment by Kas-tle** [comment]
The icon issue there has nothing to do with a duplicate identifier. It is because the converter sets the item as the vanilla icon. However, it uses the java names. Bedrock in most, but not all cases, uses the same icon names. I suppose I should make clearer in the readme that this is a limitation. You would need to make your own sprite icon for each item if you wanted them to look correct anyways, as bedrock has no way of generating the 2D inventory icon from the 3D model as java does.

**Comment by DJelly4K** [comment]
> The icon issue there has nothing to do with a duplicate identifier. It is because the converter sets the item as the vanilla icon. However, it uses the java names. Bedrock in most, but not all cases, uses the same icon names. I suppose I should make clearer in the readme that this is a limitation. You would need to make your own sprite icon for each item if you wanted them to look correct anyways, as bedrock has no way of generating the 2D inventory icon from the 3D model as java does.

well, my fault, thanks a lot anyway
