### ISSUE TITLE
[Bug]: Script doesn't check if `unzip` is installed

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Kas-tle/java2bedrock.sh#683]
### Conversion Issue Link

I'm actually running it locally

### Expected Output

It would check that `unzip` is not installed and warn the user about it.

### Actual Output

```bash
[•] Decompressing input pack
./converter.sh: line 124: unzip: command not found
[+] Input pack decompressed
[ERROR] Invalid resource pack! The pack.mcmeta file does not exist. Is the resource pack improperly compressed in an enclosing folder?
```

### Additional Context

Running Ubuntu 20.04 LTS on WSL2

**Comment by Kas-tle** [comment]
You are correct that it does not check, but if you followed the dependency installation instructions at the end of the readme you also would have installed it so... I might get around to this eventually but at a certain point it's impossible to check for every dependency.

**Comment by MrPowerGamerBR** [comment]
Derp, I was manually installing the dependencies from the "Also note that this script requires:" section because I didn't notice the  "Dependency Installation" section, my bad.
