### ISSUE TITLE
[Pack]: 

### ISSUE THREAD

**Issue by ColorsASD** [Kas-tle/java2bedrock.sh#75]
### Java Pack Direct Download URL

http://minewild.hu/storage/pack/pack.zip

### Default Assets Version

1.17.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by Kas-tle** [comment]
@ColorsASD just so you know "censoring" the pack URL after the fact will do very little as 1. The edit history of comments is fully visible on GitHub and 2. The action run will still log the URL. In the future, if you wish to not share the pack publicly, you should run the converter locally.
