### ISSUE TITLE
[Pack]: slime

### ISSUE THREAD

**Issue by pedrolep136** [Kas-tle/java2bedrock.sh#8113]
### Java Pack Direct Download URL

https://drive.google.com/uc?export=download&id=12xRDR2G9qvrEgSvZ6YJpfLQtfZqxejOt

### Default Assets Version

1.18.2

### Block Material

alpha_test

### Attachable Material

entity_emissive_alpha_one_sided

### Archive Scratch Files

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by pedrolep136** [comment]
:/

**Comment by NasastaXD** [comment]
Whats happen here?
