### ISSUE TITLE
[Bug]: Unable to find pack.mcmeta

### ISSUE THREAD

**Issue by tomhmagic** [Kas-tle/java2bedrock.sh#8225]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/8224

### Expected Output

Find pack.mecmeta and continue to convert pack

### Actual Output

Couldn't find pack.mcmeta when correctly in the root of the zip. failed to convert pack

### Additional Context

The pack.mcmeta and assets folder is correctly in the root of the zip.

**Comment by TypicalShavonne** [comment]
you cant use google drive link, you MUST use a direct download link, you can upload it to discord instead then copy the link, put it into the converter

**Comment by Michael-A-Sloan** [comment]
I seem to have this same issue as well. https://github.com/Kas-tle/java2bedrock.sh/issues/8512#issue-1772177365

**Comment by TypicalShavonne** [comment]
the pack download link MUST be direct, for example; when you click it, the download begins immediately
You can try to use dropbox or discord

**Comment by Michael-A-Sloan** [comment]
Oops sorry used the wrong url for the first part my other urls are discord sorry about that.
