### ISSUE TITLE
[Bug]: Too long names

### ISSUE THREAD

**Issue by Funasitien** [Kas-tle/java2bedrock.sh#8364]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/5309246711

### Expected Output

"The resource pack geyser_resources.mcpack has a file in it that meets or exceeds 80 characters in its path (attachables/geyser_custom/minecraft/item/amythyst_sword.gmdl_7484ef5.attachable.json, 84 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file."

**Possible solution :** add an option that reduce the name size

### Actual Output

There is any errors in the pack convertion

**Comment by BGM-DEVELOPMENT** [comment]
pleasee

**Comment by Michael-A-Sloan** [comment]
Bump and watch thanks for posting this so I didn't have too.

**Comment by munchkinth** [comment]
How can I solve this problem, can someone tell me?

**Comment by gamer50082** [comment]
Technically this isn’t a bug. But a feature request to fix the issue of long file name

**Comment by Kas-tle** [comment]
You can resolve this by using shorter file paths in the java pack.
