### ISSUE TITLE
[Bug]: Bow pulling animation is not present in coverted pack.

### ISSUE THREAD

**Issue by DDForgotten** [Kas-tle/java2bedrock.sh#8684]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/actions/runs/5400170200

### Expected Output

When the bow pulls it should transition to a different texture of the bow.

### Actual Output

The pack converter chose to make the item's mid pull animation as its default icon and the pulling animation for the bow does not show up at all.

### Additional Context

A custom bow item is used.

**Comment by Kas-tle** [comment]
Support for bows will not be added to this version of the converter.
