### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 98reesereese89** [Kas-tle/java2bedrock.sh#9378]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/9371

### Expected Output

I needed this pack converted so that my Bedrock players can see guns like the Java players do through the plugin WeaponMechanics and its resourcepack.

### Actual Output

I've loaded in the converted resource pack through geyser a couple different times and still haven't been able to see any of the models appear in game as expected. They just show up as feathers as it would without a resource pack. Also when Geyser launches it warns about some long path file names being over 80 characters or something.

**Comment by Kas-tle** [comment]
Looks fine to me.
